name: Deploy to server
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    
    - name: connect and pull
      # 'happy_cartwright' is the name of the container running the SPARQL endpoint
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && docker container stop politiquices-api && docker container rm politiquices-api && PROTOCOL="HTTP://"  IP_ADDRESS=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' happy_cartwright` && PORT="3030" && PROTOCOL_IP="$PROTOCOL$IP_ADDRESS:$PORT" && docker run -dit --env SPARQL_ENDPOINT=$PROTOCOL_IP --name politiquices-api -p 127.0.0.1:8000:8000 politiquices-api && exit"
    
    - name: cleanup
      run: rm -rf ~/.ssh


      # docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' happy_cartwright